import { dts as pluginDts } from "rollup-plugin-dts";

// Here we take all `.d.ts` files generated by `tsc` and combined them into a single one.
//   Why? In order to eliminate `export` statements that are needed between multiple `.d.ts`
//   file, but not needed for a final public API of this BeetPx framework.
//   In other words, we want framework users to
//     import { BpxSolidColor } from "@beetpx/beetpx";
//   but not
//     import { SolidColor } from "@beetpx/beetpx/dist/Color";
//   .
const config = [
  {
    input: "./.dist/index.d.ts",
    output: [{ file: "./dist/index.d.ts", format: "es" }],
    plugins: [
      pluginDts({
        // Sadly, pointing to the correct tsconfig files does not prevent
        //   dts plugin from typechecking test files inside `src/`, while
        //   they should not bother it at all (because `./.dist/index.d.ts`
        //   is the input, and not `./src/index.ts`).
        // But still, let's provide the plugin with the the correct
        //   tsconfig and not the default one.
        tsconfig: "tsconfig.compile.json",
      }),
    ],
  },
];

export default config;
