"use strict";
/// <reference path="./__IS_PROD__.d.ts" />
Object.defineProperty(exports, "__esModule", { value: true });
exports.BeetPx = exports.v_ = exports.spr_ = exports.transparent_ = exports.BpxVector2d = exports.BpxUtils = exports.BpxSprite = exports.BpxFillPattern = exports.TransparentColor = exports.BpxSolidColor = exports.BpxCompositeColor = void 0;
var Color_1 = require("./Color");
Object.defineProperty(exports, "BpxCompositeColor", { enumerable: true, get: function () { return Color_1.CompositeColor; } });
Object.defineProperty(exports, "BpxSolidColor", { enumerable: true, get: function () { return Color_1.SolidColor; } });
Object.defineProperty(exports, "TransparentColor", { enumerable: true, get: function () { return Color_1.TransparentColor; } });
var FillPattern_1 = require("./draw_api/FillPattern");
Object.defineProperty(exports, "BpxFillPattern", { enumerable: true, get: function () { return FillPattern_1.FillPattern; } });
var Sprite_1 = require("./Sprite");
Object.defineProperty(exports, "BpxSprite", { enumerable: true, get: function () { return Sprite_1.Sprite; } });
var Utils_1 = require("./Utils");
Object.defineProperty(exports, "BpxUtils", { enumerable: true, get: function () { return Utils_1.Utils; } });
var Vector2d_1 = require("./Vector2d");
Object.defineProperty(exports, "BpxVector2d", { enumerable: true, get: function () { return Vector2d_1.Vector2d; } });
var Color_2 = require("./Color");
Object.defineProperty(exports, "transparent_", { enumerable: true, get: function () { return Color_2.transparent_; } });
var Sprite_2 = require("./Sprite");
Object.defineProperty(exports, "spr_", { enumerable: true, get: function () { return Sprite_2.spr_; } });
var Vector2d_2 = require("./Vector2d");
Object.defineProperty(exports, "v_", { enumerable: true, get: function () { return Vector2d_2.v_; } });
var BeetPx_1 = require("./BeetPx");
Object.defineProperty(exports, "BeetPx", { enumerable: true, get: function () { return BeetPx_1.BeetPx; } });
