// `@notExported` is added to members here just to include this global in docs
//   generated by `typedoc` with help of `@zamiell/typedoc-plugin-not-exported`.

declare global {
  interface Window {
    /**
     * Note: the generated documentation marks this variable as "Not Exported".
     *   This is *not* true.
     *
     * @notExported
     */
    BEETPX__IS_PROD: boolean;

    /**
     * Note: the generated documentation marks this variable as "Not Exported".
     *   This is *not* true.
     *
     * @notExported
     */
    BEETPX__VERSION: string;
  }
}

// @ts-expect-error TS2304: Cannot find name '__BEETPX__IS_PROD__'.
window.BEETPX__IS_PROD = __BEETPX__IS_PROD__;
// @ts-expect-error TS2304: Cannot find name '__BEETPX__VERSION__'.
window.BEETPX__VERSION = __BEETPX__VERSION__;

export {
  type BpxImageAsset,
  type BpxImageUrl,
  type BpxJsonAsset,
  type BpxJsonUrl,
  type BpxSoundAsset,
  type BpxSoundUrl,
} from "./assets/Assets";
export { type BpxAudioPlaybackId } from "./audio/AudioPlayback";
export {
  type BpxSoundSequence,
  type BpxSoundSequenceEntry,
} from "./audio/SoundSequence";
export { type BpxBrowserType } from "./browser/BrowserTypeDetector";
export { BpxCanvasSnapshotColorMapping } from "./color/CanvasSnapshotColorMapping";
export { type BpxColorMapper } from "./color/ColorMapper";
export { BpxPatternColors } from "./color/PatternColors";
export { BpxRgbColor, type BpxRgbCssHex } from "./color/RgbColor";
export { BpxSpriteColorMapping } from "./color/SpriteColorMapping";
export { BpxDrawingPattern } from "./draw_api/DrawingPattern";
export { BpxPixels } from "./draw_api/Pixels";
export {
  BpxFont,
  type BpxArrangedGlyph,
  type BpxGlyph,
  type BpxKerningPrevCharMap,
  type BpxTextColorMarkers,
} from "./font/Font";
export { BpxFontPico8 } from "./font/FontPico8";
export { BpxFontSaint11Minimal4 } from "./font/FontSaint11Minimal4";
export { BpxFontSaint11Minimal5 } from "./font/FontSaint11Minimal5";
export { type BpxGameInputEvent } from "./game_input/GameInput";
export { type BpxGamepadType } from "./game_input/GameInputGamepad";
export { BpxGamepadTypeDetector } from "./game_input/GamepadTypeDetector";
export { type BpxGameButtonName } from "./game_input/buttons/GameButtons";
export { BpxEasing, type BpxEasingFn } from "./misc/Easing";
export { BpxVector2d } from "./misc/Vector2d";
export {
  BpxAnimatedSprite,
  type BpxImageBoundAnimatedSpriteFactory,
} from "./sprite/AnimatedSprite";
export { BpxSprite, type BpxImageBoundSpriteFactory } from "./sprite/Sprite";
export { BpxTimer } from "./timer/Timer";

export { BeetPx, b_ } from "./BeetPx";
export { BpxUtils, u_ } from "./utils/Utils";

export * from "./shorthands";
