// `@notExported` is added to members here just to include this global in docs
//   generated by `typedoc` with help of `@zamiell/typedoc-plugin-not-exported`.
declare global {
  /**
   * Note: the generated documentation marks this variable as "Not Exported".
   *   This is *not* true.
   *
   * @notExported
   */
  const BEETPX__IS_PROD: boolean;

  /**
   * Note: the generated documentation marks this variable as "Not Exported".
   *   This is *not* true.
   *
   * @notExported
   */
  const BEETPX__VERSION: string;
}

// @ts-ignore
window.BEETPX__IS_PROD = __BEETPX__IS_PROD__;
// @ts-ignore
window.BEETPX__VERSION = __BEETPX__VERSION__;

export { type BpxImageUrl, type BpxJsonUrl, type BpxSoundUrl } from "./Assets";
export {
  BpxCompositeColor,
  BpxMappingColor,
  BpxSolidColor,
  BpxTransparentColor,
  type BpxColor,
  type BpxColorId,
} from "./Color";
export { BpxEasing, type BpxEasingFn } from "./Easing";
export { BpxSprite } from "./Sprite";
export { BpxUtils } from "./Utils";
export { BpxVector2d } from "./Vector2d";
export { type BpxAudioPlaybackId } from "./audio/AudioPlayback";
export {
  type BpxSoundSequence,
  type BpxSoundSequenceEntry,
} from "./audio/SoundSequence";
export { type BpxBrowserType } from "./browser/BrowserTypeDetector";
export { type BpxColorMapping } from "./draw_api/DrawApi";
export { BpxFillPattern } from "./draw_api/FillPattern";
export { type BpxCanvasPixelsSnapshotId } from "./draw_api/canvas_pixels/CanvasPixelsSnapshot";
export { type BpxCharSprite, type BpxFont, type BpxFontId } from "./font/Font";
export { type BpxButtonName } from "./game_input/Buttons";
export { type BpxGameInputEvent } from "./game_input/GameInput";
export { type BpxGamepadType } from "./game_input/GamepadGameInput";
export { BpxTimer } from "./misc/Timer";

export { BeetPx } from "./BeetPx";

export { b_ } from "./BeetPx";
export { black_, blue_, green_, red_, transparent_, white_ } from "./Color";
export { spr_ } from "./Sprite";
export { u_ } from "./Utils";
export { v_, v_0_0_, v_1_1_ } from "./Vector2d";
export { timer_ } from "./misc/Timer";

// TODO: suggested tsconfig changes:
//       - moduleDetection force https://www.typescriptlang.org/tsconfig#moduleDetection
//       - isolated modules https://www.typescriptlang.org/tsconfig#isolatedModules
//       - verbatim module syntax https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax

// TODO: sometimes the canvas gets stretched after screen orientation change. Fix that

// TODO: consider regenerating docs and compiled files only on released versions. Like: have a version
//       bump script which asks whether it's major or minor or patch and checks if we are on `main`, then
//       generates docs etc. before the commit

// TODO: rework examples
