#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git_branch="$(git rev-parse --abbrev-ref HEAD)"

# Assumption for all `if [ "$branch" = "main" ]` blocks:
#   - we develop on branches other than `main`
#   - we release new versions on `main`

if [ "$git_branch" = "0.30.0-fixes" ]; then
  # If version got bumped in package.json, update the version in package-lock.json as well
  npm install
fi

# Make sure everything is formatted as desired
npm run format

if [ "$git_branch" = "0.30.0-fixes" ]; then
  # Make sure TypeScript types and Jest tests didn't break due to most recent changes.
  # We do this on a `main` branch only in order to allow broken tests while development
  #   is in progress.
  npm test

  # Check example projects
  cd ./examples/input-tester
  npm run format
  npm run tsc
  cd ../../
  cd ./examples/simple
  npm run format
  npm run tsc
  cd ../../
fi

# Generate up-to-date JS and .d.ts files out of the TypeScript source.
#   Thanks to this command being run on every commit, users can refer to
#   any commit of this repo in their `package.json` files and have BeetPx
#   ready to use there.
# We do this on all branches, because during engine development we might
#   want to install a specific non-versioned commit of BeetPx in a game
#   repository.
npm run compile

if [ "$git_branch" = "0.30.0-fixes" ]; then
  # Generate up-to-date HTML documentation
  npm run docs:generate
fi

# Whatever was changed due to commands above, let's add it to the commit
git add --all .
