#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# If version go bumped in package.json: to update the version in package-lock.json as well
npm install

# Make sure everything is formatted as desired
npm run format

# Make sure types are OK
npm run typecheck

# Make sure tests didn't break due to most recent changes
npm test

# Generate up-to-date JS and .d.ts files out of the TypeScript source.
#   Thanks to this command being run on every commit, users can refer to
#   any commit of this repo in their `package.json` files and have BeetPx
#   ready to use there.
npm run compile

# TODO: uncomment docs generating once you get it set to run on new version release only
# Generate up-to-date HTML documentation
#npm run docs:generate

# Whatever was changed due to commands above, let's add it to the commit
git add --all .

# TODO: visit all examples here and format their code and typecheck as well